# Generated by Django 5.1.1 on 2024-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
